version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - godot
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: golang.org/x/exp/slices
              desc: Use 'slices' instead.
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/vendored
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
