run:
  skip-dirs:
    - internal/vendored
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - gochecknoglobals
    - godot
    - godox
    - prealloc
  # don't enable:
  # - testpackage
  # - wsl
  # - lll
  # - gomnd
  # - nestif
  # - goerr113
  #
linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "golang.org/x/exp/slices"
            desc: "Use 'slices' instead."
