# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - env:
      - GO111MODULE=on
    main: ./cmd/promql-langserver
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - 386
      - arm
      - arm64

    goarm:
      - 7


archives:
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
    - "docker.io/prometheuscommunity/promql-langserver:latest"
    - "docker.io/prometheuscommunity/promql-langserver:{{ .Tag }}"
    - "docker.io/prometheuscommunity/promql-langserver:v{{ .Major }}"
    - "docker.io/prometheuscommunity/promql-langserver:v{{ .Major }}.{{ .Minor }}"
    - "quay.io/prometheuscommunity/promql-langserver:latest"
    - "quay.io/prometheuscommunity/promql-langserver:{{ .Tag }}"
    - "quay.io/prometheuscommunity/promql-langserver:v{{ .Major }}"
    - "quay.io/prometheuscommunity/promql-langserver:v{{ .Major }}.{{ .Minor }}"
